routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function ($router) {
    
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/report', function () {
	    return view('admin.pages.report.lists');
	})->name('report.index');

    Route::resource('/user', 'admin\UserController');
    Route::resource('/product', 'admin\ProductController');
    Route::resource('/mesin', 'admin\MesinController');
    Route::resource('/wastepoint', 'admin\WastepointController');


});

app/models/Mesin.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Mesin extends Model
{
    protected $fillable = [
    	'nama_mesin','aktif'
    ];
}

app/Http/Controllers/admin/MesinController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Repository\MesinRepository;

class MesinController extends Controller
{

    protected $mesin;

    public function __construct(MesinRepository $mesin)
    {
        $this->mesin = $mesin;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $where = array('aktif'=>1);
        $data = $this->mesin->lists($where);

        return view('admin.pages.mesin.lists',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.mesin.tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $validator =[
            'nama_mesin' => 'required|string',
        ];

        $message = [
            'nama_mesin.required' => 'Nama mesin belum diisi',
        ];

        $validatedData = $request->validate($validator,$message);
        
        $paramsData= array(
            'nama_mesin'      => $input['nama_mesin'],
            'aktif'     => 1
        );

        $tambah = $this->mesin->simpan($paramsData);

        return redirect()->route('mesin.index')->with('success','Mesin berhasil ditambahkan');
    }   

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->mesin->show($id);
        
        return view('admin.pages.mesin.detail',['data'=>$data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->mesin->show($id);
        
        return view('admin.pages.mesin.edit',['data'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();

        $validator =[
            'nama_mesin' => 'required|string'
        ];

        $message = [
            'nama_mesin.required' => 'Nama mesin belum diisi',
        ];

        $validatedData = $request->validate($validator,$message);
        
        $paramsData= array(
            'nama_mesin'      => $input['nama_mesin']
        );

        $edit = $this->mesin->edit($paramsData,$id);

        return redirect()->route('mesin.index')->with('success','Mesin berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hapus = $this->mesin->hapus($id);

        return redirect()->route('mesin.index')->with('success','Mesin berhasil dihapus');
    }
}

resources/views/admin/pages/mesin/detail.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Detail Mesin</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('mesin.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">

					 <div class="row">
		            <div class="col-xs-12 col-sm-12 col-md-12">
		                <div class="form-group">
		                    <strong>Nama mesin:</strong>
		                    {{ $data->nama_mesin }}
		                </div>
		            </div>
		        </div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@section('addingScriptJs')


@endsection

resources/views/admin/pages/mesin/edit.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Edit Mesin</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('mesin.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">

					@if (count($errors) > 0)
		                <div class="alert alert-danger">
		                    <ul>
		                        @foreach ($errors->all() as $error)
		                            <li>{{ $error }}</li>
		                        @endforeach
		                    </ul>
		                </div>
		           	@endif
				    <form action="{{ route('mesin.update',$data->id) }}" method="POST">
				        @csrf
				        @method('PUT')
				   
				         <div class="row">
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama mesin:</strong>
				                    <input type="text" name="nama_mesin" value="{{ $data->nama_mesin }}" class="form-control" placeholder="nama mesin">
				                </div>
				            </div>
				            
				            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
				              <button type="submit" class="btn btn-primary">SIMPAN</button>
				            </div>
				        </div>
				   
				    </form>
				</div>
			</div>
		</div>
	</div>
</div>


@endsection

@section('addingScriptJs')


@endsection

resources/views/admin/pages/mesin/lists.blade.php
@extends('admin.layouts.header')

@section('content')

<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Mesin</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">
		<!-- table section -->
		<div class="col-md-12">

			@if ($message = Session::get('success'))
		        <div class="alert alert-success">
		            <p>{{ $message }}</p>
		        </div>
		    @endif


			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						<h2>Data Mesin</h2>

					</div>

					<a class="btn btn-default pull-right" href="{{ route('mesin.create') }}">
		            	<i class="fa fa-plus"></i> Tambah
		            </a>
				</div>
				<div class="table_section padding_infor_info">
					<div class="table-responsive-sm">

						<table class="table">
							<thead>
								<tr>
									<th>id</th>
									<th>Nama Mesin</th>
									<th>Aksi</th>
								</tr>
							</thead>
							<tbody>
								@foreach($data as $key=>$value)
								<tr>
									<td>{{ $value->id }}</td>
									<td>{{ $value->nama_mesin }}</td>
									<td>
										<form action="{{ route('mesin.destroy',$value->id) }}" method="POST">
						                    @csrf
						                    @method('DELETE')


						                    <a class="btn btn-warning btn-icon" href="{{ route('mesin.edit',$value->id) }}">
						                    	<i class="fa fa-pencil"></i>
						                    </a>

						                    <a class="btn btn-success btn-icon" href="{{ route('mesin.show',$value->id) }}">
						                    	<i class="fa fa-eye"></i>
						                    </a>
						      
						                    <button type="submit" class="btn btn-danger btn-icon">
												<i class="fa fa-trash-o"></i>
											</button>

						                </form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/pages/mesin/tambah.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Tambah Mesin</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('mesin.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">



					@if (count($errors) > 0)
		                <div class="alert alert-danger">
		                    <ul>
		                        @foreach ($errors->all() as $error)
		                            <li>{{ $error }}</li>
		                        @endforeach
		                    </ul>
		                </div>
		           	@endif
				    <form action="{{ route('mesin.store') }}" method="POST">
				        @csrf
				        @method('POST')
				   
				         <div class="row">
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama mesin:</strong>
				                    <input type="text" name="nama_mesin" value="" class="form-control" placeholder="nama mesin">
				                </div>
				            </div>
				            
				            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
				              <button type="submit" class="btn btn-primary">SIMPAN</button>
				            </div>
				        </div>
				   
				    </form>
				</div>
			</div>

		</div>
		
	</div>

</div>
<!-- /.container-fluid -->

@endsection

@section('addingScriptJs')


@endsection