routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function ($router) {
    
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/report', function () {
	    return view('admin.pages.report.lists');
	})->name('report.index');

    Route::resource('/user', 'admin\UserController');
    Route::resource('/product', 'admin\ProductController');
    Route::resource('/mesin', 'admin\MesinController');
    Route::resource('/wastepoint', 'admin\WastepointController');


});

app/models/Wastepoint.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Wastepoint extends Model
{
    protected $fillable = [
    	'nama','code','mesinid','aktif'
    ];

    public function mesin()
  	{
      return $this->hasOne('App\models\Mesin', 'id','mesinid')->first();
  	}

    public function product()
    {
      return $this->hasMany('App\models\Products', 'wastepointid','id');
    }

}

app/Http/Controllers/admin/WastepointController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Repository\WastepointRepository;

class WastepointController extends Controller
{
    protected $wastepoint;

    public function __construct(WastepointRepository $wastepoint)
    {
        $this->wastepoint = $wastepoint;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $where = array('aktif'=>1);
        $data = $this->wastepoint->lists($where);

        return view('admin.pages.wastepoint.lists',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mesin = $this->wastepoint->mesin();

        $data = array();
        $data['mesin'] = $mesin;

        return view('admin.pages.wastepoint.tambah',['data'=>$data]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $validator =[
            'nama' => 'required|string',
            'code' => 'required|string',
            'mesin' => 'required|integer',
        ];

        $message = [
            'nama.required' => 'Nama wastepoint belum diisi',
            'code.required' => 'Code wastepoint belum diisi',
            'mesin.required' => 'Nama mesin belum dipilih',
        ];

        $validatedData = $request->validate($validator,$message);
        
        $paramsData= array(
            'nama'      => $input['nama'],
            'code'      => $input['code'],
            'mesinid'   => $input['mesin'],
            'aktif'     => 1
        );

        $tambah = $this->wastepoint->simpan($paramsData);

        return redirect()->route('wastepoint.index')->with('success','Wastepoint berhasil ditambahkan');
    }   

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->wastepoint->show($id);

        return view('admin.pages.wastepoint.detail',['data'=>$data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->wastepoint->show($id);
        
        $mesin = $this->wastepoint->mesin();

        $data->mesin = $mesin;
        
        return view('admin.pages.wastepoint.edit',['data'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();

        $validator =[
            'nama' => 'required|string'
        ];

        $message = [
            'nama.required' => 'Nama wastepoint belum diisi',
        ];

        $validatedData = $request->validate($validator,$message);
        
        $paramsData= array(
            'nama'      => $input['nama']
        );

        $edit = $this->wastepoint->edit($paramsData,$id);

        return redirect()->route('wastepoint.index')->with('success','Wastepoint berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hapus = $this->wastepoint->hapus($id);

        return redirect()->route('wastepoint.index')->with('success','Wastepoint berhasil dihapus');
    }
}

resources/views/admin/pages/wastepoint/detail.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Detail Mesin</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('mesin.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">

					<div class="row">
			            <div class="col-xs-12 col-sm-12 col-md-12">
			                <div class="form-group">
			                    <strong>Nama:</strong>
			                    {{ $data->nama_mesin }}
			                </div>
			            </div>

			            <div class="col-xs-12 col-sm-12 col-md-12">
		                <div class="form-group">
		                    <strong>Kode:</strong>
		                    {{ $data->code }}
		                </div>
		            </div>

		            <div class="col-xs-12 col-sm-12 col-md-12">
		                <div class="form-group">
		                    <strong>Nama mesin:</strong>
		                    {{ $data->nama_mesin }}
		                </div>
		            </div>
		        	</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('addingScriptJs')


@endsection

resources/views/admin/pages/wastepoint/edit.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Edit Waste Point</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('wastepoint.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">

					@if (count($errors) > 0)
		                <div class="alert alert-danger">
		                    <ul>
		                        @foreach ($errors->all() as $error)
		                            <li>{{ $error }}</li>
		                        @endforeach
		                    </ul>
		                </div>
		           	@endif
				    <form action="{{ route('wastepoint.update',$data->id) }}" method="POST">
				        @csrf
				        @method('PUT')
				   
				         <div class="row">
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama:</strong>
				                    <input type="text" name="nama" value="{{ $data->nama }}" class="form-control" placeholder="nama">
				                </div>
				            </div>
				            
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama Mesin:</strong>
				                     <select class="form-control" name="mesin">

				                    	<option value="">Pilih</option>

				                    	@foreach($data->mesin as $key=>$value)
				                    		<option value="{{ $value['id'] }}" {{ $data->mesinid ==  $value['id'] ? 'selected':'' }}>
				                    			{{ $value['nama_mesin'] }}
				                    		</option>
				                    	@endforeach
				                    </select>
				                </div>
				            </div>
				           	<div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Kode:</strong>
				                   <input type="text" name="code" value="{{ $data->code }}" class="form-control" placeholder="code">
				                </div>
				            </div>
				            
				            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
				              <button type="submit" class="btn btn-primary">SIMPAN</button>
				            </div>
				        </div>
				   
				    </form>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- /.container-fluid -->

@endsection

@section('addingScriptJs')


@endsection

resources/views/admin/pages/wastepoint/lists.blade.php
@extends('admin.layouts.header')

@section('content')

<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Waste Point</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">
		<!-- table section -->
		<div class="col-md-12">

			@if ($message = Session::get('success'))
		        <div class="alert alert-success">
		            <p>{{ $message }}</p>
		        </div>
		    @endif


			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						<h2>Data Waste Point</h2>
					</div>

					<a class="btn btn-default pull-right" href="{{ route('wastepoint.create') }}">
		            	<i class="fa fa-plus"></i> Tambah
		            </a>
				</div>


				<div class="table_section padding_infor_info">

					<div class="table-responsive-sm">
						<table class="table">
							<thead>
								<tr>
									<th>id</th>
									<th>Nama Mesin</th>
									<th>Nama Waste Point</th>
									<th>Kode Waste Point</th>
									<th>Aksi</th>
								</tr>
							</thead>
							<tbody>
								@foreach($data as $key=>$value)
								<tr>
									<td>{{ $value->id }}</td>
									<td>{{ $value->nama_mesin }}</td>
									<td>{{ $value->nama }}</td>
									<td>{{ $value->code }}</td>
									<td>
										<form action="{{ route('wastepoint.destroy',$value->id) }}" method="POST">
						                    @csrf
						                    @method('DELETE')


						                    <a class="btn btn-warning btn-icon btn-transparent-dark" href="{{ route('wastepoint.edit',$value->id) }}">
						                    	<i class="fa fa-pencil"></i>
						                    </a>

						                    <a class="btn btn-success btn-icon btn-transparent-dark" href="{{ route('wastepoint.show',$value->id) }}">
						                    	<i class="fa fa-eye"></i>
						                    </a>
						      
						                    <button type="submit" class="btn btn-danger btn-icon btn-transparent-dark">
												<i class="fa fa-trash-o"></i>
											</button>

						                </form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/pages/wastepoint/tambah.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Tambah Waste Point</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('wastepoint.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">



					@if (count($errors) > 0)
		                <div class="alert alert-danger">
		                    <ul>
		                        @foreach ($errors->all() as $error)
		                            <li>{{ $error }}</li>
		                        @endforeach
		                    </ul>
		                </div>
		           	@endif
				    <form action="{{ route('wastepoint.store') }}" method="POST">
				        @csrf
				        @method('POST')
				   
				         <div class="row">
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama:</strong>
				                    <input type="text" name="nama" value="" class="form-control" placeholder="nama">
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Kode:</strong>
				                    <input type="text" name="code" value="" class="form-control" placeholder="code">
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama Mesin:</strong>
				                   
				                    <select class="form-control" name="mesin">

				                    	<option value="">Pilih</option>

				                    	@foreach($data['mesin'] as $key=>$value)
				                    		<option value="{{ $value['id'] }}" {{ old('mesin') ==  $value['id'] ? 'selected':'' }}>
				                    			{{ $value['nama_mesin'] }}
				                    		</option>
				                    	@endforeach
				                    </select>
				                </div>
				            </div>


				            
				            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
				              <button type="submit" class="btn btn-primary">SIMPAN</button>
				            </div>
				        </div>
				   
				    </form>
				</div>
			</div>

		</div>
		
	</div>

</div>
<!-- /.container-fluid -->

@endsection

@section('addingScriptJs')


@endsection