routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function ($router) {
    
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/report', function () {
	    return view('admin.pages.report.lists');
	})->name('report.index');

    Route::resource('/user', 'admin\UserController');
    Route::resource('/product', 'admin\ProductController');
    Route::resource('/mesin', 'admin\MesinController');
    Route::resource('/wastepoint', 'admin\WastepointController');


});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens,Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','Aktif','kode','role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Hash;
use App\Repository\UsersRepository;

class UserController extends Controller
{
    
    protected $users;

    public function __construct(UsersRepository $users)
    {
        $this->users = $users;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $where = array('Aktif'=>1);
        $data = $this->users->lists($where);

        return view('admin.pages.user.lists',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('admin.pages.user.tambah',['data'=>[]]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $validator =[
            'name' => 'required|string',
            'email'=> 'required|email|string|unique:users',
            'password' => 'required|required_with:konfirmasi_password',
            'konfirmasi_password' => 'required|same:password'
        ];

        $message = [
            'name.required' => 'Nama belum diisi',
            'password.required' => 'Password belum diisi',
            'email.required' => 'Email belum diisi',
            'email.unique'   => 'Email sudah terdaftar',
            'konfirmasi_password.required' => 'Konfirmasi Password belum diisi',
            'konfirmasi_password.same' => 'Konfirmasi Password tidak sama'
        ];

        $validatedData = $request->validate($validator,$message);
        
        $paramsData= array(
            'name'      => $input['name'],
            'email'     => $input['email'],
            'role'      => $input['role'],
            'Aktif'     => 1
        );

        if(!empty($input['password'])){
            $paramsData['password'] = Hash::make($input['password']);
        }

        $tambah = $this->users->simpan($paramsData);

        return redirect()->route('user.index')->with('success','User berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->users->show($id);
        
        return view('admin.pages.user.detail',['data'=>$data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->users->show($id);
        
        return view('admin.pages.user.edit',['data'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();

        $validator =[
            'name' => 'required|string',
            'email'=> 'required|email|string|unique:users,email,'.$id,
            'password' => 'required_with:konfirmasi_password|same:konfirmasi_password'
        ];

        $message = [
            'name.required' => 'Nama belum diisi',
            'password.required' => 'Password belum diisi',
            'email.required' => 'Email belum diisi',
            'email.unique'   => 'Email sudah terdaftar',
            'password.same' =>  'Konfirmasi Password tidak sama'
        ];

        $validatedData = $request->validate($validator,$message);

        $paramsData= array(
            'name'      => $input['name'],
            'email'     => $input['email'],
            'role'     => $input['role'],
        );

        if(!empty($input['password'])){
            $paramsData['password'] = Hash::make($input['password']);
        }

        $update = $this->users->edit($paramsData,$id);

        return redirect()->route('user.index')->with('success','User berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hapus = $this->users->hapus($id);

        return redirect()->route('user.index')->with('success','User berhasil dihapus');
    }
}

app/Http/Controllers/api/user/UserController.php
<?php

namespace App\Http\Controllers\api\user;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\User; 
use Illuminate\Support\Facades\Auth; 
use Validator;

class UserController extends Controller
{
    public $successStatus = 200;

    /** 
     * login api 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function login(Request $request){ 

        $validator = Validator::make($request->all(), [
            'kode' => 'required|string|max:6',
            'password' => 'required|string'
        ]);

        if ($validator->fails())
        {
            return response()->json(['errors'=>$validator->errors()->all()], 422);
        }

        // $user = User::where([

        //     'kode' => $request->kode,

        // ])->first();
        
        // if ($user) {
            
        //     $success['token'] =  $user->createToken('ICWMS')->accessToken; 

        //     return response()->json(['success' => $success], $this->successStatus); 

        // } else {
            
        //     return response()->json(['error'=>'Unauthorised'], 401); 

        // }

    	if(Auth::attempt(['kode' => request('kode'), 'password' => request('password')])){ 

    		$user = Auth::user(); 
    
    		$success['token'] =  $user->createToken('ICWMS')->accessToken; 
    
    		return response()->json(['success' => $success], $this->successStatus); 
    
    	} 
    
    	else{ 
    
    		return response()->json(['error'=>'Unauthorised'], 401); 
    
    	} 
    
    }


    /** 
     * Register api 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function register(Request $request) 
    { 
    	$validator = Validator::make($request->all(), [ 
    		'name' => 'required', 
    		'email' => 'required|email', 
    		'password' => 'required', 
    		'c_password' => 'required|same:password', 
    	]);
    	if ($validator->fails()) { 
    		return response()->json(['error'=>$validator->errors()], 401);            
    	}
    	$input = $request->all(); 
    	$input['password'] = bcrypt($input['password']); 
        $input['Aktif'] = 1;
        $input['role'] = 1;
        $input['kode'] = 123456;
        
    	$user = User::create($input); 
    	$success['token'] =  $user->createToken('MyApp')->accessToken; 
    	$success['name'] =  $user->name;
    	return response()->json(['success'=>$success], $this->successStatus); 
    }

    /** 
     * details api 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function details() 
    { 
        $user = Auth::user(); 
        return response()->json(['data' => $user], $this->successStatus); 
    } 
}

resources/views/admin/pages/user/detail.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Detail User</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('user.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">

					 <div class="row">
		            <div class="col-xs-12 col-sm-12 col-md-12">
		                <div class="form-group">
		                    <strong>Nama:</strong>
		                    {{ $data->name }}
		                </div>

		                <div class="form-group">
		                    <strong>Email:</strong>
		                    {{ $data->email }}
		                </div>

		                <div class="form-group">
		                    <strong>Role:</strong>
		                    {{ $data->role }}
		                </div>
		            </div>
		        </div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

@section('addingScriptJs')


@endsection

resources/views/admin/pages/user/edit.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Edit User</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('user.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">

					@if (count($errors) > 0)
		                <div class="alert alert-danger">
		                    <ul>
		                        @foreach ($errors->all() as $error)
		                            <li>{{ $error }}</li>
		                        @endforeach
		                    </ul>
		                </div>
		           	@endif
				    <form action="{{ route('user.update',$data->id) }}" method="POST">
				        @csrf
				        @method('PUT')
				   
				         <div class="row">
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama:</strong>
				                    <input type="text" name="name" value="{{ $data->name }}" class="form-control" placeholder="">
				                </div>

				                <div class="form-group">
				                    <strong>Email:</strong>
				                    <input type="text" name="email" value="{{ $data->email }}" class="form-control" placeholder="">
				                </div>

				                <div class="form-group">
				                    <strong>Role:</strong>
				                    <select class="form-control" name="role">

				                    	<option>Pilih</option>

				                    	<option value="1" {{ $data->role == 1 ? 'selected' : '' }}> Admin </option>
				                    	<option value="2" {{ $data->role == 2 ? 'selected' : '' }}> Admin Staff </option>
				                    	<option value="3" {{ $data->role == 3 ? 'selected' : '' }}> Admin rework </option>
				                    </select>
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>password:</strong>
				                    <input type="password" id="Password" name="password" value="" class="form-control" placeholder="">
				                </div>
				            </div>
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>konfirmasi password :</strong>
				                    <input type="password" id="RePassword" name="konfirmasi_password" value="" class="form-control" placeholder="">
				                </div>
				            </div>
				            
				            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
				              <button type="submit" class="btn btn-primary">SIMPAN</button>
				            </div>
				        </div>
				   
				    </form>
				</div>
			</div>
		</div>
	</div>
</div>


@endsection

@section('addingScriptJs')


@endsection

resources/views/admin/pages/user/lists.blade.php
@extends('admin.layouts.header')

@section('content')

<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Data User</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">
		<!-- table section -->
		<div class="col-md-12">

			@if ($message = Session::get('success'))
		        <div class="alert alert-success">
		            <p>{{ $message }}</p>
		        </div>
		    @endif


			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						<h2>Data User</h2>

					</div>

					<a class="btn btn-default pull-right" href="{{ route('user.create') }}">
		            	<i class="fa fa-plus"></i> Tambah
		            </a>
				</div>
				<div class="table_section padding_infor_info">
					<div class="table-responsive-sm">

						<table class="table">
							<thead>
								<tr>
									<th>id</th>
									<th>Nama</th>
									<th>Email</th>
									<th>Aksi</th>
								</tr>
							</thead>
							<tbody>
								@foreach($data as $key=>$value)
								<tr>
									<td>{{ $value->id }}</td>
									<td>{{ $value->name }}</td>
									<td>{{ $value->email }}</td>
									<td>
										<form action="{{ route('user.destroy',$value->id) }}" method="POST">
						                    @csrf
						                    @method('DELETE')


						                    <a class="btn btn-warning btn-icon" href="{{ route('user.edit',$value->id) }}">
						                    	<i class="fa fa-pencil"></i>
						                    </a>

						                    <a class="btn btn-success btn-icon" href="{{ route('user.show',$value->id) }}">
						                    	<i class="fa fa-eye"></i>
						                    </a>
						      
						                    <button type="submit" class="btn btn-danger btn-icon">
												<i class="fa fa-trash-o"></i>
											</button>

						                </form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/pages/user/tambah.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Tambah User</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('user.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">



					@if (count($errors) > 0)
		                <div class="alert alert-danger">
		                    <ul>
		                        @foreach ($errors->all() as $error)
		                            <li>{{ $error }}</li>
		                        @endforeach
		                    </ul>
		                </div>
		           	@endif
				    <form action="{{ route('user.store') }}" method="POST">
				        @csrf
				        @method('POST')
				   
				         <div class="row">
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama:</strong>
				                    <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="">
				                </div>

				                <div class="form-group">
				                    <strong>Email:</strong>
				                    <input type="text" name="email" value="{{ old('email') }}" class="form-control" placeholder="">
				                </div>

				                <div class="form-group">
				                    <strong>Role:</strong>
				                    <select class="form-control" name="role">

				                    	<option>Pilih</option>

				                    	<option value="1" {{ old('old') == 1 ? 'selected' : '' }}> Admin </option>
				                    	<option value="2" {{ old('old') == 2 ? 'selected' : '' }}> Admin Staff </option>
				                    	<option value="3" {{ old('old') == 3 ? 'selected' : '' }}> Admin rework </option>
				                    </select>
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>password:</strong>
				                    <input type="password" id="Password" name="password" value="" class="form-control" placeholder="">
				                </div>
				            </div>
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>konfirmasi password :</strong>
				                    <input type="password" id="RePassword" name="konfirmasi_password" value="" class="form-control" placeholder="">
				                </div>
				            </div>
				            
				            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
				              <button type="submit" class="btn btn-primary">SIMPAN</button>
				            </div>
				        </div>
				   
				    </form>
				</div>
			</div>

		</div>
		
	</div>

</div>
<!-- /.container-fluid -->

@endsection

@section('addingScriptJs')


@endsection