routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function ($router) {
    
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/report', function () {
	    return view('admin.pages.report.lists');
	})->name('report.index');

    Route::resource('/user', 'admin\UserController');
    Route::resource('/product', 'admin\ProductController');
    Route::resource('/mesin', 'admin\MesinController');
    Route::resource('/wastepoint', 'admin\WastepointController');


});

app/models/Products.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    protected $fillable = [

    	'nama','code','wastepointid','harga','aktif'

    ];

    public function wastepoint()
  	{
      return $this->hasOne('App\models\Wastepoint', 'id','wastepointid')->first();
  	}

    public function materials()
    {
      return $this->hasMany('App\models\Materials', 'productid','code');
    }
}

app/Http/Controllers/admin/ProductController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Repository\ProductRepository;

class ProductController extends Controller
{

    protected $product;

    public function __construct(ProductRepository $product)
    {
        $this->product = $product;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $where = array('aktif'=>1);
        $data = $this->product->lists($where);

        return view('admin.pages.product.lists',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $wastepoint = $this->product->wastepoint();

        $data = array();
        $data['wastepoint'] = $wastepoint;

        return view('admin.pages.product.tambah',['data'=>$data]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $validator =[
            'nama' => 'required|string',
            'code' => 'required|string',
            'wastepoint' => 'required|integer',
            'harga' => 'required|integer',
        ];

        $message = [
            'nama.required'         => 'Nama Product belum diisi',
            'code.required'         => 'Code Product belum diisi',
            'wastepoint.required'   => 'Nama wastepoint belum dipilih',
            'harga.required'        => 'Nama harga belum diisi',
        ];

        $validatedData = $request->validate($validator,$message);
        
        $paramsData= array(
            'nama'      => $input['nama'],
            'code'      => $input['code'],
            'wastepointid'   => $input['wastepoint'],
            'harga'   => $input['harga'],
            'aktif'     => 1
        );

        $tambah = $this->product->simpan($paramsData);

        return redirect()->route('product.index')->with('success','Product berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->product->show($id);
        
        return view('admin.pages.product.detail',['data'=>$data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->product->show($id);
        
        $wastepoint = $this->product->wastepoint();

        $data->wastepoint = $wastepoint;
        
        return view('admin.pages.product.edit',['data'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();

        $validator =[
            'nama' => 'required|string'
        ];

        $message = [
            'nama.required' => 'Nama product belum diisi',
        ];

        $validatedData = $request->validate($validator,$message);
        
        $paramsData= array(
            'nama'      => $input['nama']
        );

        $edit = $this->product->edit($paramsData,$id);

        return redirect()->route('product.index')->with('success','Product berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hapus = $this->product->hapus($id);

        return redirect()->route('product.index')->with('success','Product berhasil dihapus');
    }
}

resources/views/admin/pages/product/detail.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">CABANG</h1>
	<p class="mb-4"></p>

	<!-- DataTales Example -->
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 col-sm-6 font-weight-bold text-primary float-left">DETAIL CABANG</h6>


			<a href="{{ route('cabang.index') }}" class="btn btn-sm btn-success float-right" type="button">
				<i class="fas fa-arrow-left"></i> Kembali
			</a>
			
		</div>
		<div class="card-body">
			
	         <div class="row">
	            <div class="col-xs-12 col-sm-12 col-md-12">
	                <div class="form-group">
	                    <strong>Nama cabang:</strong>
	                    {{ $data->nama_cabang }}
	                </div>
	            </div>
	            
	            <div class="col-xs-12 col-sm-12 col-md-12">
	                <div class="form-group">
	                    <strong>phone:</strong>
	                    {{ $data->telepon }}
	                </div>
	            </div>
	           	<div class="col-xs-12 col-sm-12 col-md-12">
	                <div class="form-group">
	                    <strong>Alamat:</strong>
	                    {{ $data->alamat }}
	                </div>
	            </div>
	            
	        </div>
		   
		</div>
	</div>

</div>
<!-- /.container-fluid -->

@endsection

@section('addingScriptJs')


@endsection

resources/views/admin/pages/product/edit.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->

<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Tambah Product</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('product.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">

					@if (count($errors) > 0)
		                <div class="alert alert-danger">
		                    <ul>
		                        @foreach ($errors->all() as $error)
		                            <li>{{ $error }}</li>
		                        @endforeach
		                    </ul>
		                </div>
		           	@endif

				    <form action="{{ route('product.update',$data->id) }}" method="POST">
				       	@csrf
				        @method('PUT')
				   
				         <div class="row">
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama Product:</strong>
				                    <input type="text" name="nama" value="{{ $data->nama }}" class="form-control" placeholder="nama">
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Kode Product:</strong>
				                    <input type="text" name="code" value="{{ $data->code }}" class="form-control" placeholder="code">
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama Waste Point:</strong>
				                   
				                    <select class="form-control" name="wastepoint">

				                    	<option value="">Pilih</option>

				                    	@foreach($data['wastepoint'] as $key=>$value)
				                    		<option value="{{ $value['id'] }}" {{ $data->wastepointid ==  $value['id'] ? 'selected':'' }}>
				                    			{{ $value['nama'] }}
				                    		</option>
				                    	@endforeach
				                    </select>
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Harga :</strong>
				                    <input type="text" name="harga" value="{{ $data->harga }}" class="form-control" placeholder="harga">
				                </div>
				            </div>
				            
				            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
				              <button type="submit" class="btn btn-primary">SIMPAN</button>
				            </div>
				        </div>
				   
				    </form>
				</div>
			</div>

		</div>
		
	</div>

</div>

<!-- /.container-fluid -->

@endsection

@section('addingScriptJs')


@endsection

resources/views/admin/pages/product/lists.blade.php
@extends('admin.layouts.header')

@section('content')

<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Product</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">
		<!-- table section -->
		<div class="col-md-12">

			@if ($message = Session::get('success'))
		        <div class="alert alert-success">
		            <p>{{ $message }}</p>
		        </div>
		    @endif


			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						<h2>Data Product</h2>
					</div>

					<a class="btn btn-default pull-right" href="{{ route('product.create') }}">
		            	<i class="fa fa-plus"></i> Tambah
		            </a>
				</div>


				<div class="table_section padding_infor_info">

					<div class="table-responsive-sm">
						<table class="table">
							<thead>
								<tr>
									<th>id</th>
									<th>Nama Products</th>
									<th>Nama Waste Point</th>
									<th>Kode Product</th>
									<th>Harga</th>
									<th>Aksi</th>
								</tr>
							</thead>
							<tbody>
								@foreach($data as $key=>$value)
								<tr>
									<td>{{ $value->id }}</td>
									<td>{{ $value->nama }}</td>
									<td>{{ $value->nama_wastepoint }}</td>
									<td>{{ $value->code }}</td>
									<td>{{ $value->harga }}</td>
									<td>
										<form action="{{ route('product.destroy',$value->id) }}" method="POST">
						                    @csrf
						                    @method('DELETE')


						                    <a class="btn btn-warning btn-icon btn-transparent-dark" href="{{ route('product.edit',$value->id) }}">
						                    	<i class="fa fa-pencil"></i>
						                    </a>

						                    <a class="btn btn-success btn-icon btn-transparent-dark" href="{{ route('product.show',$value->id) }}">
						                    	<i class="fa fa-eye"></i>
						                    </a>
						      
						                    <button type="submit" class="btn btn-danger btn-icon btn-transparent-dark">
												<i class="fa fa-trash-o"></i>
											</button>

						                </form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/pages/product/tambah.blade.php
@extends('admin.layouts.header')

@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">
	<div class="row column_title">
		<div class="col-md-12">
			<div class="page_title">
				<h2>Tambah Product</h2>
			</div>
		</div>
	</div>
	<!-- row -->
	<div class="row">

		<div class="col-md-12">
			
			<div class="white_shd full margin_bottom_30">
				<div class="full graph_head">
					<div class="heading1 margin_0">
						
						<a href="{{ route('product.index') }}" class="btn btn-sm btn-success float-right" type="button">
						<i class="fa fa-arrow-left"></i> Kembali
					</a>
					</div>
				</div>
				<div class="table_section padding_infor_info">



					@if (count($errors) > 0)
		                <div class="alert alert-danger">
		                    <ul>
		                        @foreach ($errors->all() as $error)
		                            <li>{{ $error }}</li>
		                        @endforeach
		                    </ul>
		                </div>
		           	@endif
				    <form action="{{ route('product.store') }}" method="POST">
				        @csrf
				        @method('POST')
				   
				         <div class="row">
				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama Product:</strong>
				                    <input type="text" name="nama" value="{{ old('nama') }}" class="form-control" placeholder="nama">
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Kode Product:</strong>
				                    <input type="text" name="code" value="{{ old('code') }}" class="form-control" placeholder="code">
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Nama Waste Point:</strong>
				                   
				                    <select class="form-control" name="wastepoint">

				                    	<option value="">Pilih</option>

				                    	@foreach($data['wastepoint'] as $key=>$value)
				                    		<option value="{{ $value['id'] }}" {{ old('wastepoint') ==  $value['id'] ? 'selected':'' }}>
				                    			{{ $value['nama'] }}
				                    		</option>
				                    	@endforeach
				                    </select>
				                </div>
				            </div>

				            <div class="col-xs-12 col-sm-12 col-md-12">
				                <div class="form-group">
				                    <strong>Harga :</strong>
				                    <input type="text" name="harga" value="{{ old('harga') }}" class="form-control" placeholder="harga">
				                </div>
				            </div>
				            
				            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
				              <button type="submit" class="btn btn-primary">SIMPAN</button>
				            </div>
				        </div>
				   
				    </form>
				</div>
			</div>

		</div>
		
	</div>

</div>
<!-- /.container-fluid -->

@endsection

@section('addingScriptJs')


@endsection